# Generated by Django 5.2 on 2025-04-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DistrictWeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("pm10", models.FloatField(blank=True, null=True)),
                ("pm2_5", models.FloatField(blank=True, null=True)),
                ("avg_temp", models.FloatField(blank=True, null=True)),
                ("avg_pm2_5", models.FloatField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["avg_temp", "avg_pm2_5"],
            },
        ),
    ]
